
services:
  userservices:
    container_name: userservices-api
    image: userservice_img
    build:
      context: ../
      dockerfile: src/UserServices/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - network-microservice 
    links:
      - consul
    depends_on:
      - consul
    
  libraryservices:
    container_name: libraryservices-api
    image: libraryservice_img
    build:
      context: ../
      dockerfile: src/LibraryService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - network-microservice
    links:
      - consul
    depends_on:
      - consul

  studentservices:
    container_name: studentservices-api
    image: studentservice_img
    build:
      context: ../
      dockerfile: src/StudentService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - network-microservice
    links:
      - consul
    depends_on:
      - consul

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: annex_apigateway
    build:
      context: ../
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:80"
    networks:
      - network-gateway
      - network-microservice
    links:
      - consul
      - studentservices
      - libraryservices
      - userservices
    depends_on:
      - consul